layout_spectrum: 0.5248931252863258
typography_spectrum: 0.8106354451738298
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7922802688553929
  lightness: 0.8074599620886147
  saturation: 0.5295823540072888
  rhythmicContrast: 0.3968817312270403
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Papaland
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Papaland
description: 'Observations of a first-time father in Berlin, Germany'
purpose: []
